### PR TITLE
Fix compilation with java 8: the order was not predictable

### PR DESCRIPTION
**Pull request by mathbagu**
**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
N/A

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Bug fix

**What is the current behavior?** *(You can also link to an open issue here)*
The compilation fails with Java 8 due to an unpredictable order in the DynawoContext.

**What is the new behavior (if this is a feature change)?**
We now use a `TreeMap` to have a predictable order of the dynamic models

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

### CODE REVIEW

**Review by gautierbureau — APPROVED** [review]

**Review by zamarrenolm — COMMENTED** [review]
Why is relevant the order of black box models in the context ? If we "hide" the fact that the order is relevant only in the implementation of the underlying map we are postponing the issue

**Comment by mathbagu** [comment]
> Why is relevant the order of black box models in the context ? If we "hide" the fact that the order is relevant only in the implementation of the underlying map we are postponing the issue

I think I miss something: the index in the PAR file should match with the index in the DYD file. In the PAR file, the index is based on the alphabetical order whereas in the DYD file, it's based on the declaration order. I have to check a little bit more deeply if we shouldn't replace the `TreeMap` by a `LinkedHashMap`.

@zamarrenolm: the order is important when indexes are used. I'm not sure it's important to expose this in the API, if the implementation ensure that the iteration order is the same than the declarative order.

**Comment by zamarrenolm** [comment]
> > Why is relevant the order of black box models in the context ? If we "hide" the fact that the order is relevant only in the implementation of the underlying map we are postponing the issue
> 
> I think I miss something: the index in the PAR file should match with the index in the DYD file. In the PAR file, the index is based on the alphabetical order whereas in the DYD file, it's based on the declaration order. I have to check a little bit more deeply if we shouldn't replace the `TreeMap` by a `LinkedHashMap`.
> 
> @zamarrenolm: the order is important when indexes are used. I'm not sure it's important to expose this in the API, if the implementation ensure that the iteration order is the same than the declarative order.

Then maybe we should force iteration same iteration when building indexes, to make it explicit, instead of hiding that requirement in the implementation of the underlying collection?

**Comment by zamarrenolm** [comment]
> > > Why is relevant the order of black box models in the context ? If we "hide" the fact that the order is relevant only in the implementation of the underlying map we are postponing the issue
> > 
> > 
> > I think I miss something: the index in the PAR file should match with the index in the DYD file. In the PAR file, the index is based on the alphabetical order whereas in the DYD file, it's based on the declaration order. I have to check a little bit more deeply if we shouldn't replace the `TreeMap` by a `LinkedHashMap`.
> > @zamarrenolm: the order is important when indexes are used. I'm not sure it's important to expose this in the API, if the implementation ensure that the iteration order is the same than the declarative order.
> 
> Then maybe we should force iteration same iteration when building indexes, to make it explicit, instead of hiding that requirement in the implementation of the underlying collection?

I understand that the `blackBoxModels` stored in the `DynawoXmlContext` have to preserve the same ordering (explicit) that is given by the original `List` of all `dynamicModels` stored in `DynawoContext`. `DynawoXmlContext` stores only the ones that are black box, but it must preserve the same order in which they are defined in the "main" list.

**Comment by zamarrenolm** [comment]
> > > > Why is relevant the order of black box models in the context ? If we "hide" the fact that the order is relevant only in the implementation of the underlying map we are postponing the issue
> > > 
> > > 
> > > I think I miss something: the index in the PAR file should match with the index in the DYD file. In the PAR file, the index is based on the alphabetical order whereas in the DYD file, it's based on the declaration order. I have to check a little bit more deeply if we shouldn't replace the `TreeMap` by a `LinkedHashMap`.
> > > @zamarrenolm: the order is important when indexes are used. I'm not sure it's important to expose this in the API, if the implementation ensure that the iteration order is the same than the declarative order.
> > 
> > 
> > Then maybe we should force iteration same iteration when building indexes, to make it explicit, instead of hiding that requirement in the implementation of the underlying collection?
> 
> I understand that the `blackBoxModels` stored in the `DynawoXmlContext` have to preserve the same ordering (explicit) that is given by the original `List` of all `dynamicModels` stored in `DynawoContext`. `DynawoXmlContext` stores only the ones that are black box, but it must preserve the same order in which they are defined in the "main" list.

The order of `dynamicModels` in the DYD will not be alphabetical, it will follow the order in which the supplier (`DynamicModelsSupplier`) has decided to provide them. So, we have to take this order as the reference. It is given as a List, as an ordered collection.

**Comment by zamarrenolm** [comment]
> > > > > Why is relevant the order of black box models in the context ? If we "hide" the fact that the order is relevant only in the implementation of the underlying map we are postponing the issue
> > > > 
> > > > 
> > > > I think I miss something: the index in the PAR file should match with the index in the DYD file. In the PAR file, the index is based on the alphabetical order whereas in the DYD file, it's based on the declaration order. I have to check a little bit more deeply if we shouldn't replace the `TreeMap` by a `LinkedHashMap`.
> > > > @zamarrenolm: the order is important when indexes are used. I'm not sure it's important to expose this in the API, if the implementation ensure that the iteration order is the same than the declarative order.
> > > 
> > > 
> > > Then maybe we should force iteration same iteration when building indexes, to make it explicit, instead of hiding that requirement in the implementation of the underlying collection?
> > 
> > 
> > I understand that the `blackBoxModels` stored in the `DynawoXmlContext` have to preserve the same ordering (explicit) that is given by the original `List` of all `dynamicModels` stored in `DynawoContext`. `DynawoXmlContext` stores only the ones that are black box, but it must preserve the same order in which they are defined in the "main" list.
> 
> The order of `dynamicModels` in the DYD will not be alphabetical, it will follow the order in which the supplier (`DynamicModelsSupplier`) has decided to provide them. So, we have to take this order as the reference. It is given as a List, as an ordered collection.

Creating a TreeMap will sort the black box models by its key, not necessarily according to the original order provided by the supplier, that is what we should use as reference. 

I propose that we just collect filtered black boxes to a list and then build the map. We answer questions for a black box by id using the map, and when the whole collection is requested, we return the list. What do you think ?

**Comment by zamarrenolm** [comment]
@mathbagu, @gautierbureau : I made a commit to fix the bug. I have fixed the unit test for `ieee57-disconnectgenerator`: originally the weights in `OmegaRef` (calculated as `H*SNom` of generator) did not correspond to the order in which generators appear in the DYD. Now the indexes in `omegaRef` will always be generated following the order of declaration of dynamic models in the DYD.

**Comment by zamarrenolm** [comment]
the test `ieee57-disconnectgenerators` also shows that the declaration order in the DYD does not need to be alphabetical by model id. Generators appear in the order 6, 8, 12, 1, 3, 9, 2.

**Comment by mathbagu** [comment]
@zamarrenolm Thanks for your proposal. I also tried by replacing the `TreeMap::new` by `LinkedHashMap::new` in my first try and it works. Do you think this simple change won't fix the issue?

**Comment by zamarrenolm** [comment]
> @zamarrenolm Thanks for your proposal. I also tried by replacing the `TreeMap::new` by `LinkedHashMap::new` in my first try and it works. Do you think this simple change won't fix the issue?

Yes, the LinkedHashMap solution will also work because it will preserve the original order, it stores the values following insertion order. It is equivalent to the combination of a List+Map that I proposed.

**Review by zamarrenolm — APPROVED** [review]
Added a comment in the output of `OmegaRef` parameters about the order.

**Review by gautierbureau — APPROVED** [review]

**Pull request merged**
