### PR TITLE
Module refactoring

### PR DESCRIPTION
**Pull request by marcosmc**
**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
#67

### CODE REVIEW

**Review by geofjamg — CHANGES_REQUESTED** [review]
Dynaflow or DynaFlow
DynaWaltz or Dynawaltz

In the code this is always Dynaflow and most of the time DynaWaltz (and a few Dynawaltz like DynawaltzCurveGroovyExtension). We have to choose if we keep the uppercase or not and be consistent everywhere.
@marcosmc @zamarrenolm personnally I would keep the upper case but anyway the only important thing is to be consistent everywhere. What would you go for?

**Comment by zamarrenolm** [comment]
> Dynaflow or DynaFlow
> DynaWaltz or Dynawaltz
> 
> In the code this is always Dynaflow and most of the time DynaWaltz (and a few Dynawaltz like DynawaltzCurveGroovyExtension). We have to choose if we keep the uppercase or not and be consistent everywhere.
> @marcosmc @zamarrenolm personnally I would keep the upper case but anyway the only important thing is to be consistent everywhere. What would you go for?

Totally agree on being consistent.

I would vote too for keeping the uppercase: DynaWaltz and DynaFlow.

**Review by geofjamg — CHANGES_REQUESTED** [review]
Both dynawaltz and dynawaltz-dsl use com.powsybl.dynawaltz package which is forbidden with Java9 modules (this is asplit package). So  dynawaltz-dsl should use com.powsybl.dynawaltz.dsl

**Comment by marcosmc** [comment]
> Both dynawaltz and dynawaltz-dsl use com.powsybl.dynawaltz package which is forbidden with Java9 modules (this is asplit package). So dynawaltz-dsl should use com.powsybl.dynawaltz.dsl

I have verified that in dynamic-simulation-dsl the package `com.powsybl.dynamicsimulation.groovy` is used instead of `com.powsybl.dynamicsimulation.dsl`. What do you think of using the same nomenclature `com.powsybl.dynawaltz.groovy`?

**Comment by geofjamg** [comment]
> dynamic-simulation-dsl

I would fix dynamic-simulation-dsl instead because I like when artifact id is consistent with package

**Review by geofjamg — APPROVED** [review]

**Review by zamarrenolm — APPROVED** [review]

**Pull request merged**
